### ISSUE TITLE
Error when importing into Unity.

### ISSUE THREAD

**Issue by LugiNess** [heyjoeway/ICBINS1#1]
Whenever I open this in Unity, I get the same error every time.

**Comment by heyjoeway** [comment]
...start by doing what the error says and install git. You also will need to install git-lfs and clone the project using git instead of downloading a zip from GitHub.

**Comment by LugiNess** [comment]
Sorry for the late response.
So I installed Git, and cloned the package. I put it in a folder, opened it with the right version of Unity and it gave me the same error.
Git is telling me, "fatal: could not create work tree dir 'ICBINS1': Permission denied"
I'm typing into Git-cmd, "C:\Program Files\Git> git clone https://github.com/heyjoeway/ICBINS1.git"
